1. select a.*, c.CUST_NAME FROM agents a, customer c WHERE a.AGENT_CODE = c.AGENT_CODE;
2. select o.ORD_NUM, o.ORD_DATE, c.CUST_NAME, a.AGENT_NAME FROM agents a, custom
er c, orders o WHERE a.AGENT_CODE = o.AGENT_CODE AND c.CUST_CODE=o.CUST_CODE;
3. select a.AGENT_NAME, c.CUST_NAME, o.ORD_DATE, o.ORD_AMOUNT FROM agents a, cus
tomer c, orders o WHERE a.AGENT_CODE = o.AGENT_CODE AND c.CUST_CODE=o.CUST_CODE AND
c.CUST_COUNTRY='Canada';
4. select c.CUST_NAME, o.ORD_NUM, o.ORD_AMOUNT FROM customer c, orders o WHERE c
.CUST_CODE=o.CUST_CODE AND c.CUST_CITY='New York';
5. select a.AGENT_NAME, c.CUST_NAME, o.ORD_NUM, o.ORD_AMOUNT FROM agents a, cust
omer c, orders o WHERE a.AGENT_CODE = o.AGENT_CODE AND c.CUST_CODE=o.CUST_CODE AND o.ORD_AMOUNT>1500;
6. select o.*, a.* FROM agents a, orders o WHERE a.AGENT_CODE=o.AGENT_CODE;
7. select c.CUST_NAME, c.CUST_CODE, c.OUTSTANDING_AMT, a.AGENT_NAME FROM agents
a, customer c WHERE a.AGENT_CODE = c.AGENT_CODE AND c.OUTSTANDING_AMT>=6000;
8. select c.CUST_NAME, o.ORD_NUM, o.ORD_AMOUNT, o.ADVANCE_AMOUNT FROM customer c, orders o WHERE c.CUST_CODE=o.CUST_CODE AND o.ORD_AMOUNT >=2500 OR o.ADVANCE_AMOUNT<300;
9. select a.AGENT_NAME, a.WORKING_AREA, c.CUST_NAME, c.WORKING_AREA FROM customer c, agents a WHERE c.AGENT_CODE=a.AGENT_CODE AND a.WORKING_AREA = c.WORKING_AREA;
10. select c.CUST_NAME, a.AGENT_NAME, o.ORD_NUM FROM agents a, customer c, orders
 o WHERE a.AGENT_CODE = o.AGENT_CODE AND c.CUST_CODE=o.CUST_CODE AND o.ORD_AMOUNT<10
00 OR c.OPENING_AMT>8000;